name: csvIntegrationTest
apis:
  - name: read
    file: $$TMP\test payloads\test.csv
    add_attribute:
      fullName: ${last}, ${first}
    custom_attributes:
      agenda: customers
    strip_keys:
      - number
